import type { Product } from "@/lib/data";

// Data real dari C:/Users/Panji/Downloads/STOCK BAHAN BAKU GUDANG ARFARM.xlsx
export const realStockProducts: Product[] = [
  {
    "sku": "AFJ-BB-001",
    "barcode": "ARF00001",
    "name": "beras jathil",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 347500,
    "retailPrice": 347500,
    "minStock": 5,
    "maxStock": 37,
    "currentStock": 17,
    "initialStock": 17,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-002",
    "barcode": "ARF00002",
    "name": "beras SPHP",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 59500,
    "retailPrice": 59500,
    "minStock": 5,
    "maxStock": 101,
    "currentStock": 81,
    "initialStock": 100,
    "stockIn": 0,
    "stockOut": 19,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-003",
    "barcode": "ARF00003",
    "name": "gula pasir",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "kg",
    "purchasePrice": 16500,
    "retailPrice": 16500,
    "minStock": 5,
    "maxStock": 106,
    "currentStock": 43,
    "initialStock": 2,
    "stockIn": 43,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-004",
    "barcode": "ARF00004",
    "name": "garam kasar 400 gr",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 2750,
    "retailPrice": 2750,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260618",
    "expirationDate": "2026-06-18",
    "status": "Habis",
    "lastUpdate": "2026-06-18"
  },
  {
    "sku": "AFJ-BB-005",
    "barcode": "ARF00005",
    "name": "garam halus segitiga",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 1450,
    "retailPrice": 1450,
    "minStock": 5,
    "maxStock": 103,
    "currentStock": 83,
    "initialStock": 83,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-006",
    "barcode": "ARF00006",
    "name": "garam grosok",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 15000,
    "retailPrice": 15000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Habis",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-007",
    "barcode": "ARF00007",
    "name": "kecap asin ABC 620 ml",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 18000,
    "retailPrice": 18000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Habis",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-008",
    "barcode": "ARF00008",
    "name": "royco ayam 1 kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 38700,
    "retailPrice": 38700,
    "minStock": 5,
    "maxStock": 80,
    "currentStock": 60,
    "initialStock": 60,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260703",
    "expirationDate": "2026-07-03",
    "status": "Tersedia",
    "lastUpdate": "2026-07-03"
  },
  {
    "sku": "AFJ-BB-009",
    "barcode": "ARF00009",
    "name": "royco sapi 1 kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "kg",
    "purchasePrice": 38700,
    "retailPrice": 38700,
    "minStock": 5,
    "maxStock": 24,
    "currentStock": 4,
    "initialStock": 4,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260601",
    "expirationDate": "2026-06-01",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-01"
  },
  {
    "sku": "AFJ-BB-010",
    "barcode": "ARF00010",
    "name": "knorr ayam",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "kg",
    "purchasePrice": 90350,
    "retailPrice": 90350,
    "minStock": 5,
    "maxStock": 25,
    "currentStock": 5,
    "initialStock": 5,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-011",
    "barcode": "ARF00011",
    "name": "tepung tapioka 500 gr",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 7000,
    "retailPrice": 7000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 5,
    "stockIn": 0,
    "stockOut": 5,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260609",
    "expirationDate": "2026-06-09",
    "status": "Habis",
    "lastUpdate": "2026-06-09"
  },
  {
    "sku": "AFJ-BB-012",
    "barcode": "ARF00012",
    "name": "tepung panir",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karung",
    "purchasePrice": 100000,
    "retailPrice": 100000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260604",
    "expirationDate": "2026-06-04",
    "status": "Habis",
    "lastUpdate": "2026-06-04"
  },
  {
    "sku": "AFJ-BB-013",
    "barcode": "ARF00013",
    "name": "tepung maizena 25 kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "kg",
    "purchasePrice": 14000,
    "retailPrice": 14000,
    "minStock": 5,
    "maxStock": 45,
    "currentStock": 25,
    "initialStock": 25,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-014",
    "barcode": "ARF00014",
    "name": "tepung terigu cakra kembar",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karung",
    "purchasePrice": 230000,
    "retailPrice": 230000,
    "minStock": 5,
    "maxStock": 22,
    "currentStock": 2,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Stok Rendah",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-015",
    "barcode": "ARF00015",
    "name": "Miwon 1kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 45208,
    "retailPrice": 45208,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260616",
    "expirationDate": "2026-06-16",
    "status": "Habis",
    "lastUpdate": "2026-06-16"
  },
  {
    "sku": "AFJ-BB-016",
    "barcode": "ARF00016",
    "name": "Msg Sasa",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 44208,
    "retailPrice": 44208,
    "minStock": 5,
    "maxStock": 21,
    "currentStock": 1,
    "initialStock": 4,
    "stockIn": 0,
    "stockOut": 3,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-017",
    "barcode": "ARF00017",
    "name": "SKM Omela (490 Gr)",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 12500,
    "retailPrice": 12500,
    "minStock": 5,
    "maxStock": 24,
    "currentStock": 4,
    "initialStock": 11,
    "stockIn": 0,
    "stockOut": 7,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-018",
    "barcode": "ARF00018",
    "name": "carnation 488 gr",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "kaleng",
    "purchasePrice": 13800,
    "retailPrice": 13800,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 3,
    "stockIn": 0,
    "stockOut": 3,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Habis",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-019",
    "barcode": "ARF00019",
    "name": "dairy champ 2,5 kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pouch",
    "purchasePrice": 56875,
    "retailPrice": 56875,
    "minStock": 5,
    "maxStock": 27,
    "currentStock": 7,
    "initialStock": 8,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-020",
    "barcode": "ARF00020",
    "name": "santan kara 1 L",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 59000,
    "retailPrice": 59000,
    "minStock": 5,
    "maxStock": 28,
    "currentStock": 8,
    "initialStock": 10,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260620",
    "expirationDate": "2026-06-20",
    "status": "Tersedia",
    "lastUpdate": "2026-06-20"
  },
  {
    "sku": "AFJ-BB-021",
    "barcode": "ARF00021",
    "name": "kecap udang",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 13500,
    "retailPrice": 13500,
    "minStock": 5,
    "maxStock": 28,
    "currentStock": 5,
    "initialStock": 4,
    "stockIn": 3,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260618",
    "expirationDate": "2026-06-18",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-18"
  },
  {
    "sku": "AFJ-BB-022",
    "barcode": "ARF00022",
    "name": "soda kue kopoe 178 gr",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 5000,
    "retailPrice": 5000,
    "minStock": 5,
    "maxStock": 30,
    "currentStock": 10,
    "initialStock": 10,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Tersedia",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-023",
    "barcode": "ARF00023",
    "name": "baking powder kopoe",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 8000,
    "retailPrice": 8000,
    "minStock": 5,
    "maxStock": 24,
    "currentStock": 4,
    "initialStock": 4,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-024",
    "barcode": "ARF00024",
    "name": "sakura agar-agar",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "box",
    "purchasePrice": 39168,
    "retailPrice": 39168,
    "minStock": 5,
    "maxStock": 31,
    "currentStock": 11,
    "initialStock": 14,
    "stockIn": 0,
    "stockOut": 3,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-025",
    "barcode": "ARF00025",
    "name": "minyak lentera mas",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 180000,
    "retailPrice": 180000,
    "minStock": 5,
    "maxStock": 27,
    "currentStock": 7,
    "initialStock": 7,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-026",
    "barcode": "ARF00026",
    "name": "minyak nutura",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 234000,
    "retailPrice": 234000,
    "minStock": 5,
    "maxStock": 56,
    "currentStock": 36,
    "initialStock": 50,
    "stockIn": 0,
    "stockOut": 14,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-027",
    "barcode": "ARF00027",
    "name": "saus raja rasa 600 ml",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 22100,
    "retailPrice": 22100,
    "minStock": 5,
    "maxStock": 42,
    "currentStock": 11,
    "initialStock": 1,
    "stockIn": 11,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-028",
    "barcode": "ARF00028",
    "name": "saori saus tiram 1L",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "botol",
    "purchasePrice": 51000,
    "retailPrice": 51000,
    "minStock": 5,
    "maxStock": 32,
    "currentStock": 6,
    "initialStock": 2,
    "stockIn": 6,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260616",
    "expirationDate": "2026-06-16",
    "status": "Tersedia",
    "lastUpdate": "2026-06-16"
  },
  {
    "sku": "AFJ-BB-029",
    "barcode": "ARF00029",
    "name": "bawang putih kupas 1 kg",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 27500,
    "retailPrice": 27500,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260611",
    "expirationDate": "2026-06-11",
    "status": "Habis",
    "lastUpdate": "2026-06-11"
  },
  {
    "sku": "AFJ-BB-030",
    "barcode": "ARF00030",
    "name": "kerupuk finna udang",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 95000,
    "retailPrice": 95000,
    "minStock": 5,
    "maxStock": 44,
    "currentStock": 24,
    "initialStock": 32,
    "stockIn": 0,
    "stockOut": 8,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260618",
    "expirationDate": "2026-06-18",
    "status": "Tersedia",
    "lastUpdate": "2026-06-18"
  },
  {
    "sku": "AFJ-BB-031",
    "barcode": "ARF00031",
    "name": "sari kacang ijo 100 ml (48 pcs)",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 99250,
    "retailPrice": 99250,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 3,
    "stockIn": 0,
    "stockOut": 3,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260601",
    "expirationDate": "2026-06-01",
    "status": "Habis",
    "lastUpdate": "2026-06-01"
  },
  {
    "sku": "AFJ-BB-032",
    "barcode": "ARF00032",
    "name": "sari kacang ijo 100 ml (48 pcs) new",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 92000,
    "retailPrice": 92000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 31,
    "stockIn": 0,
    "stockOut": 31,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260525",
    "expirationDate": "2026-05-25",
    "status": "Habis",
    "lastUpdate": "2026-05-25"
  },
  {
    "sku": "AFJ-BB-033",
    "barcode": "ARF00033",
    "name": "sari kacang ijo 200 ml (24 pcs)",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 85000,
    "retailPrice": 85000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260520",
    "expirationDate": "2026-05-20",
    "status": "Habis",
    "lastUpdate": "2026-05-20"
  },
  {
    "sku": "AFJ-BB-034",
    "barcode": "ARF00034",
    "name": "sari kacang ijo 200 ml (24 pcs) new",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 90000,
    "retailPrice": 90000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260601",
    "expirationDate": "2026-06-01",
    "status": "Habis",
    "lastUpdate": "2026-06-01"
  },
  {
    "sku": "AFJ-BB-035",
    "barcode": "ARF00035",
    "name": "susu ff nutribrain (110ml) 36 pcs",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 117000,
    "retailPrice": 117000,
    "minStock": 5,
    "maxStock": 283,
    "currentStock": 263,
    "initialStock": 427,
    "stockIn": 0,
    "stockOut": 164,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Tersedia",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-036",
    "barcode": "ARF00036",
    "name": "susu sekolah cimory 125 ml (40 pcs)",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 128000,
    "retailPrice": 128000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260712",
    "expirationDate": "2026-07-12",
    "status": "Habis",
    "lastUpdate": "2026-07-12"
  },
  {
    "sku": "AFJ-BB-037",
    "barcode": "ARF00037",
    "name": "nobo oatmilk creamy 200 ml",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 62000,
    "retailPrice": 62000,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 56,
    "stockIn": 0,
    "stockOut": 56,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260604",
    "expirationDate": "2026-06-04",
    "status": "Habis",
    "lastUpdate": "2026-06-04"
  },
  {
    "sku": "AFJ-BB-038",
    "barcode": "ARF00038",
    "name": "nobo oatmilk creamy 200 ml (gudang barat)",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "karton",
    "purchasePrice": 67200,
    "retailPrice": 67200,
    "minStock": 5,
    "maxStock": 31,
    "currentStock": 11,
    "initialStock": 20,
    "stockIn": 0,
    "stockOut": 9,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260611",
    "expirationDate": "2026-06-11",
    "status": "Tersedia",
    "lastUpdate": "2026-06-11"
  },
  {
    "sku": "AFJ-BB-039",
    "barcode": "ARF00039",
    "name": "rafia hitam",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "ball",
    "purchasePrice": 145000,
    "retailPrice": 145000,
    "minStock": 5,
    "maxStock": 26,
    "currentStock": 4,
    "initialStock": 2,
    "stockIn": 2,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-040",
    "barcode": "ARF00040",
    "name": "rafia warna",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "ball",
    "purchasePrice": 155000,
    "retailPrice": 155000,
    "minStock": 5,
    "maxStock": 29,
    "currentStock": 9,
    "initialStock": 9,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260610",
    "expirationDate": "2026-06-10",
    "status": "Tersedia",
    "lastUpdate": "2026-06-10"
  },
  {
    "sku": "AFJ-BB-041",
    "barcode": "ARF00041",
    "name": "kresek oval warna 25x35 (50 pcs)",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 21,
    "currentStock": 1,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260429",
    "expirationDate": "2026-04-29",
    "status": "Stok Rendah",
    "lastUpdate": "2026-04-29"
  },
  {
    "sku": "AFJ-BB-042",
    "barcode": "ARF00042",
    "name": "kresek oval putih 25*35",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 21750,
    "retailPrice": 21750,
    "minStock": 5,
    "maxStock": 53,
    "currentStock": 33,
    "initialStock": 53,
    "stockIn": 0,
    "stockOut": 20,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260505",
    "expirationDate": "2026-05-05",
    "status": "Tersedia",
    "lastUpdate": "2026-05-05"
  },
  {
    "sku": "AFJ-BB-043",
    "barcode": "ARF00043",
    "name": "kresek oval 20x30 (50 pcs)",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 11550,
    "retailPrice": 11550,
    "minStock": 5,
    "maxStock": 85,
    "currentStock": 65,
    "initialStock": 65,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260504",
    "expirationDate": "2026-05-04",
    "status": "Tersedia",
    "lastUpdate": "2026-05-04"
  },
  {
    "sku": "AFJ-BB-044",
    "barcode": "ARF00044",
    "name": "kresek merah",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 15625,
    "retailPrice": 15625,
    "minStock": 5,
    "maxStock": 32,
    "currentStock": 12,
    "initialStock": 40,
    "stockIn": 0,
    "stockOut": 28,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260611",
    "expirationDate": "2026-06-11",
    "status": "Tersedia",
    "lastUpdate": "2026-06-11"
  },
  {
    "sku": "AFJ-BB-045",
    "barcode": "ARF00045",
    "name": "thinwall 150 ml cup tutup",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "slop",
    "purchasePrice": 14000,
    "retailPrice": 14000,
    "minStock": 5,
    "maxStock": 26,
    "currentStock": 6,
    "initialStock": 8,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260418",
    "expirationDate": "2026-04-18",
    "status": "Tersedia",
    "lastUpdate": "2026-04-18"
  },
  {
    "sku": "AFJ-BB-046",
    "barcode": "ARF00046",
    "name": "thinwall 100 ml cup tutup",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "slop",
    "purchasePrice": 18000,
    "retailPrice": 18000,
    "minStock": 5,
    "maxStock": 22,
    "currentStock": 2,
    "initialStock": 6,
    "stockIn": 0,
    "stockOut": 4,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260618",
    "expirationDate": "2026-06-18",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-18"
  },
  {
    "sku": "AFJ-BB-047",
    "barcode": "ARF00047",
    "name": "thinwall 200 ml",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "slop",
    "purchasePrice": 17500,
    "retailPrice": 17500,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 6,
    "stockIn": 0,
    "stockOut": 6,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260512",
    "expirationDate": "2026-05-12",
    "status": "Habis",
    "lastUpdate": "2026-05-12"
  },
  {
    "sku": "AFJ-BB-048",
    "barcode": "ARF00048",
    "name": "thinwall 350 ml",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "slop",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 4,
    "stockIn": 0,
    "stockOut": 4,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260517",
    "expirationDate": "2026-05-17",
    "status": "Habis",
    "lastUpdate": "2026-05-17"
  },
  {
    "sku": "AFJ-BB-049",
    "barcode": "ARF00049",
    "name": "cup 10 oz",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 66,
    "currentStock": 46,
    "initialStock": 59,
    "stockIn": 0,
    "stockOut": 13,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260520",
    "expirationDate": "2026-05-20",
    "status": "Tersedia",
    "lastUpdate": "2026-05-20"
  },
  {
    "sku": "AFJ-BB-050",
    "barcode": "ARF00050",
    "name": "cup 60 ml",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 22,
    "currentStock": 2,
    "initialStock": 16,
    "stockIn": 0,
    "stockOut": 14,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260601",
    "expirationDate": "2026-06-01",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-01"
  },
  {
    "sku": "AFJ-BB-051",
    "barcode": "ARF00051",
    "name": "cup 100 ml",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 37,
    "currentStock": 9,
    "initialStock": 1,
    "stockIn": 8,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Tersedia",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-052",
    "barcode": "ARF00052",
    "name": "sendok jelly",
    "category": "Bahan Baku",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 4130,
    "retailPrice": 4130,
    "minStock": 5,
    "maxStock": 76,
    "currentStock": 56,
    "initialStock": 71,
    "stockIn": 0,
    "stockOut": 15,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-053",
    "barcode": "ARF00053",
    "name": "sarung tangan plastik bestaft",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 6950,
    "retailPrice": 6950,
    "minStock": 5,
    "maxStock": 35,
    "currentStock": 15,
    "initialStock": 31,
    "stockIn": 0,
    "stockOut": 16,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-054",
    "barcode": "ARF00054",
    "name": "sarung tangan nitrile",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "box",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 0,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Habis",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-055",
    "barcode": "ARF00055",
    "name": "OPP 7x10",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 36,
    "currentStock": 16,
    "initialStock": 16,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Tersedia",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-056",
    "barcode": "ARF00056",
    "name": "OPP 11x11",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 11,
    "stockIn": 0,
    "stockOut": 11,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Habis",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-057",
    "barcode": "ARF00057",
    "name": "OPP 9x9",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 48,
    "currentStock": 28,
    "initialStock": 29,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Tersedia",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-058",
    "barcode": "ARF00058",
    "name": "OPP 14*14",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 5300,
    "retailPrice": 5300,
    "minStock": 5,
    "maxStock": 30,
    "currentStock": 10,
    "initialStock": 10,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-059",
    "barcode": "ARF00059",
    "name": "OPP 120x060",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 35,
    "currentStock": 15,
    "initialStock": 25,
    "stockIn": 0,
    "stockOut": 10,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Tersedia",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-060",
    "barcode": "ARF00060",
    "name": "OPP 100x60",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Habis",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-061",
    "barcode": "ARF00061",
    "name": "plastik klip matahari 8,7*13",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 6500,
    "retailPrice": 6500,
    "minStock": 5,
    "maxStock": 26,
    "currentStock": 6,
    "initialStock": 10,
    "stockIn": 0,
    "stockOut": 4,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260616",
    "expirationDate": "2026-06-16",
    "status": "Tersedia",
    "lastUpdate": "2026-06-16"
  },
  {
    "sku": "AFJ-BB-062",
    "barcode": "ARF00062",
    "name": "plastik klip matahari 7*10",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 27,
    "currentStock": 7,
    "initialStock": 10,
    "stockIn": 0,
    "stockOut": 3,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260616",
    "expirationDate": "2026-06-16",
    "status": "Tersedia",
    "lastUpdate": "2026-06-16"
  },
  {
    "sku": "AFJ-BB-063",
    "barcode": "ARF00063",
    "name": "plastik es batu",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 2,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Habis",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-064",
    "barcode": "ARF00064",
    "name": "plastik tutup sealer",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "roll",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 21,
    "currentStock": 1,
    "initialStock": 2,
    "stockIn": 0,
    "stockOut": 1,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260601",
    "expirationDate": "2026-06-01",
    "status": "Stok Rendah",
    "lastUpdate": "2026-06-01"
  },
  {
    "sku": "AFJ-BB-065",
    "barcode": "ARF00065",
    "name": "tissue 180 lembar passcoy",
    "category": "Operasional",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 4600,
    "retailPrice": 4600,
    "minStock": 5,
    "maxStock": 29,
    "currentStock": 9,
    "initialStock": 24,
    "stockIn": 0,
    "stockOut": 15,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-066",
    "barcode": "ARF00066",
    "name": "tissue 250 jolly",
    "category": "Operasional",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 7250,
    "retailPrice": 7250,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 0,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260427",
    "expirationDate": "2026-04-27",
    "status": "Habis",
    "lastUpdate": "2026-04-27"
  },
  {
    "sku": "AFJ-BB-067",
    "barcode": "ARF00067",
    "name": "masker hitam",
    "category": "Operasional",
    "brand": "AR Farm Jaya",
    "unit": "pcs",
    "purchasePrice": 7000,
    "retailPrice": 7000,
    "minStock": 5,
    "maxStock": 48,
    "currentStock": 28,
    "initialStock": 34,
    "stockIn": 0,
    "stockOut": 6,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-068",
    "barcode": "ARF00068",
    "name": "haircap",
    "category": "Operasional",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 33600,
    "retailPrice": 33600,
    "minStock": 5,
    "maxStock": 40,
    "currentStock": 20,
    "initialStock": 26,
    "stockIn": 0,
    "stockOut": 6,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-069",
    "barcode": "ARF00069",
    "name": "sabun cuci",
    "category": "Operasional",
    "brand": "AR Farm Jaya",
    "unit": "jerigen",
    "purchasePrice": 50000,
    "retailPrice": 50000,
    "minStock": 5,
    "maxStock": 109,
    "currentStock": 89,
    "initialStock": 100,
    "stockIn": 0,
    "stockOut": 11,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260617",
    "expirationDate": "2026-06-17",
    "status": "Tersedia",
    "lastUpdate": "2026-06-17"
  },
  {
    "sku": "AFJ-BB-070",
    "barcode": "ARF00070",
    "name": "mika 4A (290ml)",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "pack",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 20,
    "currentStock": 0,
    "initialStock": 5,
    "stockIn": 0,
    "stockOut": 5,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260504",
    "expirationDate": "2026-05-04",
    "status": "Habis",
    "lastUpdate": "2026-05-04"
  },
  {
    "sku": "AFJ-BB-071",
    "barcode": "ARF00071",
    "name": "plastik wrapping",
    "category": "Kemasan",
    "brand": "AR Farm Jaya",
    "unit": "roll",
    "purchasePrice": 0,
    "retailPrice": 0,
    "minStock": 5,
    "maxStock": 21,
    "currentStock": 1,
    "initialStock": 1,
    "stockIn": 0,
    "stockOut": 0,
    "rack": "BB-01-01",
    "warehouse": "Gudang Bahan Baku",
    "supplier": "Data Stock Gudang ARFARM",
    "batch": "STOCK-20260504",
    "expirationDate": "2026-05-04",
    "status": "Stok Rendah",
    "lastUpdate": "2026-05-04"
  }
];
